extends Reference

class_name CollisionStatic

const WORLD_LAYER = 0x0001
const METEOROID_LAYER = 0x0002
const SPACESHIP_LAYER = 0x0004
const ITEM_LAYER = 0x0008 

const WORLD_MASK = 0
const METEOROID_MASK = WORLD_LAYER | METEOROID_LAYER | SPACESHIP_LAYER
const SPACESHIP_MASK = WORLD_LAYER | METEOROID_LAYER | SPACESHIP_LAYER
const ITEM_MASK      = WORLD_LAYER |                   SPACESHIP_LAYER | ITEM_LAYER

